name: main
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python_version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Setup Nox
      run: |
        pip install --upgrade pip
        pip install nox
    - name: Lint
      run: |
        nox -s lint
    - name: Test
      run: |
        nox -s test-${{ matrix.python_version }}